apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: oyekunmi2/dotnet-personal-starter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: REDIS_PORT
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: MSSQL_CONNECTIONSTRING

---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  type: NodePort
  selector:
    app: products
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30500