apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: dotnet-personal-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: MSSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: dotnet-personal-starter
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433